<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.jeegit</groupId>
        <artifactId>jeegit</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>jeegit-framework</artifactId>
    <packaging>pom</packaging>
    <description>JeeGit 核心框架模块</description>

    <modules>
        <module>jeegit-framework-security</module>
        <module>jeegit-framework-mybatis</module>
        <module>jeegit-framework-web</module>
        <module>jeegit-framework-excel</module>
    </modules>
</project>
